<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Str;
use App\Models\ExploreWabagSection;
use App\Models\ExploreWabagItem;

class ExploreWabagDetailedSeeder extends Seeder
{
    public function run(): void
    {
        ExploreWabagSection::updateOrCreate(
            ['title' => 'Explore Wabag District'],
            [
                'subtitle' => 'Discover the rich cultural heritage and natural beauty of our Highlands home',
                'is_published' => true,
            ]
        );

        $list = function (array $items): array {
            return array_map(fn ($value) => ['value' => $value], $items);
        };

        $records = [
            // TREK / ADVENTURE (5)
            [
                'category_label' => 'TREKKING',
                'title' => 'Highlands Ridge Walks (Wabag Area)',
                'description' => 'Short guided ridge walks that showcase dramatic Highlands views around Wabag.',
                'detail_intro' => 'These walks are ideal for visitors who want a half‑day adventure with wide valley views and cool mountain air.',
                'highlights' => $list([
                    'Ridge-top viewpoints with wide valley panoramas',
                    'Cool mornings and clear light for photography',
                    'Opportunities to learn local place names and stories',
                ]),
                'tips' => $list([
                    'Start early for clearer skies',
                    'Bring a light rain jacket',
                    'Arrange a local guide for the best viewpoints',
                ]),
                'checklist' => $list([
                    'Sturdy walking shoes',
                    'Water and light snacks',
                    'Sun protection',
                ]),
                'itinerary' => $list([
                    'Meet local guide in Wabag Town',
                    'Walk to ridge lookout and rest stop',
                    'Return via village path',
                ]),
                'locations' => $list([
                    'Wabag Town outskirts',
                    'Ridge lookouts above the valley',
                ]),
                'best_time' => 'Dry mornings and clear-weather days',
                'duration' => '2–4 hours',
                'difficulty' => 'Easy to moderate',
                'opening_hours' => 'Daylight hours',
                'price_info' => 'Guide fees vary by group size',
                'getting_there' => 'Start from Wabag Town and arrange a local guide or transport to nearby trailheads.',
                'safety_notes' => 'Stay on established paths and monitor weather conditions.',
                'contact_info' => 'Contact local tourism coordinators or the district office for guides.',
                'icon' => 'nature',
                'link_label' => 'Plan a Trek',
                'sort_order' => 1,
            ],
            [
                'category_label' => 'TREKKING',
                'title' => 'Valley View Walks',
                'description' => 'Gentle walks to scenic overlooks for families and first‑time visitors.',
                'detail_intro' => 'A relaxed option with minimal elevation gain and plenty of photo stops.',
                'highlights' => $list([
                    'Short routes with big views',
                    'Great for families and small groups',
                    'Cool, breezy conditions',
                ]),
                'tips' => $list([
                    'Bring a camera or phone with extra battery',
                    'Wear layers for changing temperatures',
                ]),
                'checklist' => $list([
                    'Comfortable walking shoes',
                    'Water bottle',
                ]),
                'itinerary' => $list([
                    'Depart from town center',
                    'Stop at main viewpoint',
                    'Return to town for lunch',
                ]),
                'locations' => $list([
                    'Wabag viewpoints',
                ]),
                'best_time' => 'Morning light for photos',
                'duration' => '1–2 hours',
                'difficulty' => 'Easy',
                'opening_hours' => 'Daylight hours',
                'price_info' => 'No fixed fee; guide optional',
                'getting_there' => 'Short drive or walk from Wabag Town.',
                'safety_notes' => 'Stay clear of steep edges and keep children close.',
                'contact_info' => 'District tourism contacts can recommend local guides.',
                'icon' => 'nature',
                'link_label' => 'Plan a Trek',
                'sort_order' => 2,
            ],
            [
                'category_label' => 'TREKKING',
                'title' => 'Cloud Forest Day Walk',
                'description' => 'A longer guided walk through misty forest zones outside Wabag.',
                'detail_intro' => 'Expect lush vegetation, birdlife, and cooler temperatures.',
                'highlights' => $list([
                    'Cloud forest vegetation and birdlife',
                    'Quiet forest ambience',
                    'Guided nature interpretation',
                ]),
                'tips' => $list([
                    'Pack a rain jacket',
                    'Bring insect repellent',
                ]),
                'checklist' => $list([
                    'Rain jacket',
                    'Light snacks',
                    'Insect repellent',
                ]),
                'itinerary' => $list([
                    'Drive to trailhead',
                    'Guided forest loop',
                    'Return to town by afternoon',
                ]),
                'locations' => $list([
                    'Forest areas near Wabag',
                ]),
                'best_time' => 'Dry season mornings',
                'duration' => '4–6 hours',
                'difficulty' => 'Moderate',
                'opening_hours' => 'Daylight hours',
                'price_info' => 'Guide fees apply',
                'getting_there' => 'Arrange a vehicle from Wabag Town to the trailhead.',
                'safety_notes' => 'Do not trek alone; weather can change quickly.',
                'contact_info' => 'Local guides available through district tourism contacts.',
                'icon' => 'nature',
                'link_label' => 'Plan a Trek',
                'sort_order' => 3,
            ],
            [
                'category_label' => 'TREKKING',
                'title' => 'River Valley Walks',
                'description' => 'Walks along river valleys with farmland views and village visits.',
                'detail_intro' => 'Combine light walking with local community visits and produce tasting.',
                'highlights' => $list([
                    'Riverside paths and gardens',
                    'Village hospitality opportunities',
                    'Local produce sampling',
                ]),
                'tips' => $list([
                    'Ask permission before entering gardens',
                    'Bring small cash for local produce',
                ]),
                'checklist' => $list([
                    'Comfortable shoes',
                    'Small cash',
                ]),
                'itinerary' => $list([
                    'Start at valley entrance',
                    'Walk to village garden areas',
                    'Return via river path',
                ]),
                'locations' => $list([
                    'Valley paths near Wabag',
                ]),
                'best_time' => 'Late morning or early afternoon',
                'duration' => '2–3 hours',
                'difficulty' => 'Easy to moderate',
                'opening_hours' => 'Daylight hours',
                'price_info' => 'No fixed fee',
                'getting_there' => 'Short drive from Wabag Town.',
                'safety_notes' => 'Watch footing near water and slippery rocks.',
                'contact_info' => 'Community coordinators can arrange visits.',
                'icon' => 'nature',
                'link_label' => 'Plan a Trek',
                'sort_order' => 4,
            ],
            [
                'category_label' => 'TREKKING',
                'title' => 'Sunrise Lookout Walks',
                'description' => 'Early morning walks for sunrise views and cooler temperatures.',
                'detail_intro' => 'A short, rewarding outing for photographers and early risers.',
                'highlights' => $list([
                    'Soft morning light',
                    'Panoramic sunrise views',
                    'Short, low‑effort route',
                ]),
                'tips' => $list([
                    'Bring a warm layer',
                    'Leave before dawn for sunrise',
                ]),
                'checklist' => $list([
                    'Warm layer',
                    'Flashlight or headlamp',
                ]),
                'itinerary' => $list([
                    'Depart before dawn',
                    'Arrive at lookout for sunrise',
                    'Return after sunrise',
                ]),
                'locations' => $list([
                    'Lookouts near Wabag',
                ]),
                'best_time' => 'Early morning',
                'duration' => '1–2 hours',
                'difficulty' => 'Easy',
                'opening_hours' => 'Daylight hours',
                'price_info' => 'No fixed fee',
                'getting_there' => 'Short drive from Wabag Town.',
                'safety_notes' => 'Use lights on early starts; watch footing.',
                'contact_info' => 'Local guides available on request.',
                'icon' => 'nature',
                'link_label' => 'Plan a Trek',
                'sort_order' => 5,
            ],

            // MARKETS & AGRICULTURE (5)
            [
                'category_label' => 'MARKETS',
                'title' => 'Wabag Town Market',
                'description' => 'The main market in Wabag with fresh produce and local goods.',
                'detail_intro' => 'A modern market facility serves vendors and visitors with improved amenities and safety features.',
                'highlights' => $list([
                    'Fresh Highlands vegetables and fruits',
                    'Dedicated areas for vendors',
                    'Improved market facilities',
                ]),
                'tips' => $list([
                    'Arrive early for the best selection',
                    'Bring small cash and reusable bags',
                ]),
                'checklist' => $list([
                    'Small cash',
                    'Reusable shopping bag',
                ]),
                'itinerary' => $list([
                    'Morning market visit',
                    'Coffee or snack break',
                    'Return to town center',
                ]),
                'locations' => $list([
                    'Wabag Town market area',
                ]),
                'best_time' => 'Morning hours',
                'duration' => '1–2 hours',
                'difficulty' => 'Easy access',
                'opening_hours' => 'Daily, morning to late afternoon',
                'price_info' => 'Varies by vendor',
                'getting_there' => 'Located in Wabag Town with easy access from main roads.',
                'safety_notes' => 'Keep valuables secure and stay aware of surroundings.',
                'contact_info' => 'Market management or district office can assist vendors and visitors.',
                'icon' => 'community',
                'link_label' => 'Visit Markets',
                'sort_order' => 6,
            ],
            [
                'category_label' => 'MARKETS',
                'title' => 'Food Depot & Produce Hub',
                'description' => 'Storage and aggregation point for fresh produce destined for larger markets.',
                'detail_intro' => 'A food depot supports local growers with storage and handling of fresh produce.',
                'highlights' => $list([
                    'Cold storage for produce',
                    'Supports larger market supply chains',
                    'Benefits local growers',
                ]),
                'tips' => $list([
                    'Coordinate with local growers for access',
                    'Plan early for bulk purchases',
                ]),
                'checklist' => $list([
                    'Cooler boxes for transport',
                    'Bulk purchase plan',
                ]),
                'itinerary' => $list([
                    'Meet local growers',
                    'Visit depot for bulk produce',
                    'Arrange transport',
                ]),
                'locations' => $list([
                    'Wabag food depot area',
                ]),
                'best_time' => 'Weekdays during business hours',
                'duration' => '1–2 hours',
                'difficulty' => 'Easy access',
                'opening_hours' => 'Business hours',
                'price_info' => 'Varies by produce',
                'getting_there' => 'Arrange local transport from Wabag Town.',
                'safety_notes' => 'Follow depot safety and loading guidance.',
                'contact_info' => 'District agriculture or market offices can provide access details.',
                'icon' => 'community',
                'link_label' => 'Visit Markets',
                'sort_order' => 7,
            ],
            [
                'category_label' => 'MARKETS',
                'title' => 'Weekend Village Markets',
                'description' => 'Smaller weekend markets hosted by surrounding communities.',
                'detail_intro' => 'These markets rotate by village and offer a more intimate local experience.',
                'highlights' => $list([
                    'Fresh seasonal produce',
                    'Community crafts and small goods',
                    'Friendly village atmosphere',
                ]),
                'tips' => $list([
                    'Ask locals for market schedule',
                    'Bring small denominations',
                ]),
                'checklist' => $list([
                    'Small cash',
                    'Reusable bag',
                ]),
                'itinerary' => $list([
                    'Travel to a nearby village',
                    'Browse stalls and local produce',
                    'Return to Wabag Town',
                ]),
                'locations' => $list([
                    'Villages around Wabag District',
                ]),
                'best_time' => 'Weekend mornings',
                'duration' => '2–3 hours',
                'difficulty' => 'Easy',
                'opening_hours' => 'Weekend mornings',
                'price_info' => 'Low-cost local produce',
                'getting_there' => 'Arrange local transport or ride share.',
                'safety_notes' => 'Travel with a local guide when visiting new areas.',
                'contact_info' => 'Community leaders can confirm locations.',
                'icon' => 'community',
                'link_label' => 'Visit Markets',
                'sort_order' => 8,
            ],
            [
                'category_label' => 'MARKETS',
                'title' => 'Roadside Produce Stalls',
                'description' => 'Small stalls along main routes with seasonal produce and snacks.',
                'detail_intro' => 'Great for quick stops and tasting local Highlands produce.',
                'highlights' => $list([
                    'Quick roadside access',
                    'Seasonal fruit and vegetables',
                    'Local snacks',
                ]),
                'tips' => $list([
                    'Carry small cash',
                    'Ask about seasonal items',
                ]),
                'checklist' => $list([
                    'Small cash',
                ]),
                'itinerary' => $list([
                    'Stop during travel',
                    'Purchase local produce',
                ]),
                'locations' => $list([
                    'Main roads around Wabag District',
                ]),
                'best_time' => 'Daytime',
                'duration' => '15–30 minutes',
                'difficulty' => 'Easy',
                'opening_hours' => 'Daylight hours',
                'price_info' => 'Low-cost local produce',
                'getting_there' => 'Accessible by vehicle along main routes.',
                'safety_notes' => 'Pull over safely when stopping.',
                'contact_info' => 'No formal contact.',
                'icon' => 'community',
                'link_label' => 'Visit Markets',
                'sort_order' => 9,
            ],
            [
                'category_label' => 'MARKETS',
                'title' => 'Coffee & Sweet Potato Stalls',
                'description' => 'Local growers sell coffee and staple Highlands produce.',
                'detail_intro' => 'A good place to sample local flavors and support growers.',
                'highlights' => $list([
                    'Local coffee beans and brews',
                    'Highlands sweet potato varieties',
                    'Direct support to farmers',
                ]),
                'tips' => $list([
                    'Ask about roast and origin',
                    'Try seasonal varieties',
                ]),
                'checklist' => $list([
                    'Small cash',
                ]),
                'itinerary' => $list([
                    'Visit market stalls',
                    'Sample local coffee',
                ]),
                'locations' => $list([
                    'Wabag Town market area',
                ]),
                'best_time' => 'Morning hours',
                'duration' => '30–60 minutes',
                'difficulty' => 'Easy',
                'opening_hours' => 'Daily, morning to late afternoon',
                'price_info' => 'Varies by vendor',
                'getting_there' => 'Walk or drive to the market area.',
                'safety_notes' => 'Keep valuables secure.',
                'contact_info' => 'Market staff can assist with directions.',
                'icon' => 'community',
                'link_label' => 'Visit Markets',
                'sort_order' => 10,
            ],

            // HERITAGE & CULTURE (5)
            [
                'category_label' => 'HERITAGE',
                'title' => 'Enga Cultural Show (Wabag)',
                'description' => 'A vibrant annual cultural festival showcasing traditional dances, rituals, and crafts.',
                'detail_intro' => 'Held at Aipus Rugby Field in Wabag, the show features cultural groups from across Enga and the Highlands.',
                'highlights' => $list([
                    'Mass sing‑sing performances',
                    'Traditional rituals and ceremonies',
                    'Craft demonstrations and displays',
                ]),
                'tips' => $list([
                    'Arrive early for the main parade',
                    'Bring sun protection and water',
                ]),
                'checklist' => $list([
                    'Sun hat and sunscreen',
                    'Water bottle',
                ]),
                'itinerary' => $list([
                    'Morning arrival at showgrounds',
                    'Watch sing‑sing performances',
                    'Visit craft and skills area',
                ]),
                'locations' => $list([
                    'Aipus Rugby Field, Wabag',
                ]),
                'best_time' => 'Annual show in August; 9am–4pm during show days',
                'duration' => 'Full day',
                'difficulty' => 'Easy access',
                'opening_hours' => '9am–4pm during show days',
                'price_info' => 'Admission fees apply',
                'getting_there' => 'Wabag Town hosts the showgrounds at Aipus Rugby Field.',
                'safety_notes' => 'Stay within designated areas and follow event guidance.',
                'contact_info' => 'Enga Cultural Show Society: contact@engashow.com; +675 547-0126 / +675 547-1224.',
                'icon' => 'cultural',
                'link_label' => 'Learn More',
                'sort_order' => 11,
            ],
            [
                'category_label' => 'HERITAGE',
                'title' => 'Take Anda Museum',
                'description' => 'A museum in Wabag showcasing Enga history, customs, and oral traditions.',
                'detail_intro' => 'The museum preserves extensive research and artifacts from Enga’s cultural history.',
                'highlights' => $list([
                    'Historical artifacts and oral history',
                    'Traditional values and sayings',
                    'Cultural education exhibits',
                ]),
                'tips' => $list([
                    'Allow at least 1–2 hours for exhibits',
                    'Ask staff about guided explanations',
                ]),
                'checklist' => $list([
                    'Camera (where permitted)',
                    'Notebook for cultural notes',
                ]),
                'itinerary' => $list([
                    'Arrive in Wabag Town',
                    'Visit museum exhibits',
                    'Stop by nearby cultural sites',
                ]),
                'locations' => $list([
                    'Take Anda Museum, Wabag Town',
                ]),
                'best_time' => 'Daily, 9am–5pm',
                'duration' => '1–2 hours',
                'difficulty' => 'Easy access',
                'opening_hours' => '9am–5pm daily',
                'price_info' => 'Admission charges apply',
                'getting_there' => 'Located in Wabag Town, about 30 minutes from Wapenamanda Airport.',
                'safety_notes' => 'Respect museum guidelines and exhibits.',
                'contact_info' => 'Museum staff can provide current admission details.',
                'icon' => 'cultural',
                'link_label' => 'Learn More',
                'sort_order' => 12,
            ],
            [
                'category_label' => 'HERITAGE',
                'title' => 'Oral History & Storytelling',
                'description' => 'Community-led storytelling sessions sharing Enga customs and history.',
                'detail_intro' => 'Elders share ancestral knowledge, migration stories, and cultural values.',
                'highlights' => $list([
                    'First‑hand oral history',
                    'Cultural values and customs',
                    'Community participation',
                ]),
                'tips' => $list([
                    'Seek permission and be respectful',
                    'Bring a small gift for hosts if appropriate',
                ]),
                'checklist' => $list([
                    'Notebook or audio recorder (with permission)',
                ]),
                'itinerary' => $list([
                    'Arrange visit with a host community',
                    'Join storytelling session',
                ]),
                'locations' => $list([
                    'Village communities near Wabag',
                ]),
                'best_time' => 'By arrangement',
                'duration' => '1–2 hours',
                'difficulty' => 'Easy',
                'opening_hours' => 'By arrangement',
                'price_info' => 'Community contribution appreciated',
                'getting_there' => 'Coordinate through local community contacts.',
                'safety_notes' => 'Follow community protocols and guidance.',
                'contact_info' => 'District cultural office can assist with introductions.',
                'icon' => 'cultural',
                'link_label' => 'Learn More',
                'sort_order' => 13,
            ],
            [
                'category_label' => 'HERITAGE',
                'title' => 'Sing‑Sing Preparations',
                'description' => 'Behind‑the‑scenes look at sing‑sing preparations and costume making.',
                'detail_intro' => 'Learn how headdresses, body paint, and costumes are prepared for performances.',
                'highlights' => $list([
                    'Costume and headdress making',
                    'Traditional instruments and rhythm',
                    'Community rehearsal sessions',
                ]),
                'tips' => $list([
                    'Ask before taking photographs',
                    'Support local makers by purchasing crafts',
                ]),
                'checklist' => $list([
                    'Small cash for crafts',
                ]),
                'itinerary' => $list([
                    'Meet community coordinator',
                    'Observe preparation sessions',
                ]),
                'locations' => $list([
                    'Community areas in Wabag District',
                ]),
                'best_time' => 'Leading up to cultural events',
                'duration' => '1–2 hours',
                'difficulty' => 'Easy',
                'opening_hours' => 'By arrangement',
                'price_info' => 'Community contribution appreciated',
                'getting_there' => 'Arrange through local coordinators.',
                'safety_notes' => 'Respect cultural protocols.',
                'contact_info' => 'District cultural office can assist.',
                'icon' => 'cultural',
                'link_label' => 'Learn More',
                'sort_order' => 14,
            ],
            [
                'category_label' => 'HERITAGE',
                'title' => 'Traditional Crafts & Ceremonies',
                'description' => 'Experience Enga crafts and ceremonial practices guided by local elders.',
                'detail_intro' => 'A closer look at the symbolism and skills behind Enga craftwork and ceremonies.',
                'highlights' => $list([
                    'Craft demonstrations',
                    'Cultural explanations by elders',
                    'Community engagement',
                ]),
                'tips' => $list([
                    'Be respectful of restricted practices',
                    'Support crafts by purchasing locally',
                ]),
                'checklist' => $list([
                    'Small cash for crafts',
                ]),
                'itinerary' => $list([
                    'Community welcome',
                    'Craft demonstration',
                ]),
                'locations' => $list([
                    'Village communities in Wabag District',
                ]),
                'best_time' => 'By arrangement',
                'duration' => '1–3 hours',
                'difficulty' => 'Easy',
                'opening_hours' => 'By arrangement',
                'price_info' => 'Community contribution appreciated',
                'getting_there' => 'Coordinate via local community leaders.',
                'safety_notes' => 'Follow cultural guidelines.',
                'contact_info' => 'District cultural office can assist.',
                'icon' => 'cultural',
                'link_label' => 'Learn More',
                'sort_order' => 15,
            ],

            // NATURE (5)
            [
                'category_label' => 'NATURE',
                'title' => 'Highlands Landscapes',
                'description' => 'Wide valleys and mountain views that define the Wabag Highlands.',
                'detail_intro' => 'Ideal for photography and short scenic drives.',
                'highlights' => $list([
                    'Mountain ridges and valley views',
                    'Cool climate and fresh air',
                    'Scenic roadside stops',
                ]),
                'tips' => $list([
                    'Golden hour for best photos',
                    'Pack layers for cooler weather',
                ]),
                'checklist' => $list([
                    'Camera or phone',
                    'Warm layer',
                ]),
                'itinerary' => $list([
                    'Morning scenic drive',
                    'Stop at viewpoints',
                ]),
                'locations' => $list([
                    'Viewpoints around Wabag',
                ]),
                'best_time' => 'Clear mornings',
                'duration' => '1–3 hours',
                'difficulty' => 'Easy access',
                'opening_hours' => 'Daylight hours',
                'price_info' => 'No fixed fee',
                'getting_there' => 'Accessible by road from Wabag Town.',
                'safety_notes' => 'Use caution at steep viewpoints.',
                'contact_info' => 'Local tourism contacts can suggest routes.',
                'icon' => 'nature',
                'link_label' => 'Explore',
                'sort_order' => 16,
            ],
            [
                'category_label' => 'NATURE',
                'title' => 'River & Waterfall Picnics',
                'description' => 'Quiet riverside spots for relaxing and short walks.',
                'detail_intro' => 'A good option for families and small groups.',
                'highlights' => $list([
                    'Freshwater streams and rivers',
                    'Picnic-friendly areas',
                    'Gentle walking routes',
                ]),
                'tips' => $list([
                    'Bring your own picnic supplies',
                    'Leave no trace',
                ]),
                'checklist' => $list([
                    'Picnic blanket',
                    'Reusable containers',
                ]),
                'itinerary' => $list([
                    'Short drive to riverside area',
                    'Picnic and light walk',
                ]),
                'locations' => $list([
                    'Rivers near Wabag District',
                ]),
                'best_time' => 'Midday or afternoon',
                'duration' => '2–4 hours',
                'difficulty' => 'Easy',
                'opening_hours' => 'Daylight hours',
                'price_info' => 'No fixed fee',
                'getting_there' => 'Local transport from Wabag Town.',
                'safety_notes' => 'Watch footing near water.',
                'contact_info' => 'Local guides can suggest safe spots.',
                'icon' => 'nature',
                'link_label' => 'Explore',
                'sort_order' => 17,
            ],
            [
                'category_label' => 'NATURE',
                'title' => 'Cloud Forest Birding',
                'description' => 'Birdwatching in misty forest areas around Wabag.',
                'detail_intro' => 'Great for nature lovers and photographers.',
                'highlights' => $list([
                    'Unique Highlands birdlife',
                    'Quiet forest atmosphere',
                    'Cool climate',
                ]),
                'tips' => $list([
                    'Bring binoculars',
                    'Walk quietly to spot birds',
                ]),
                'checklist' => $list([
                    'Binoculars',
                    'Light rain jacket',
                ]),
                'itinerary' => $list([
                    'Morning forest walk',
                    'Birdwatching at key spots',
                ]),
                'locations' => $list([
                    'Forest zones near Wabag',
                ]),
                'best_time' => 'Early morning',
                'duration' => '2–3 hours',
                'difficulty' => 'Moderate',
                'opening_hours' => 'Daylight hours',
                'price_info' => 'Guide fees apply',
                'getting_there' => 'Arrange a guide and transport.',
                'safety_notes' => 'Stay with guide; weather can shift quickly.',
                'contact_info' => 'Local guides available through tourism contacts.',
                'icon' => 'nature',
                'link_label' => 'Explore',
                'sort_order' => 18,
            ],
            [
                'category_label' => 'NATURE',
                'title' => 'Sunset Viewpoints',
                'description' => 'Evening viewpoints for sunset colors over the Highlands.',
                'detail_intro' => 'Perfect for photographers and relaxed evening outings.',
                'highlights' => $list([
                    'Warm evening light',
                    'Wide skyline views',
                    'Short return walks',
                ]),
                'tips' => $list([
                    'Bring a warm layer for cooler evenings',
                ]),
                'checklist' => $list([
                    'Warm jacket',
                ]),
                'itinerary' => $list([
                    'Late afternoon departure',
                    'Sunset at viewpoint',
                    'Return before dark',
                ]),
                'locations' => $list([
                    'Lookouts near Wabag',
                ]),
                'best_time' => 'Late afternoon',
                'duration' => '1–2 hours',
                'difficulty' => 'Easy',
                'opening_hours' => 'Daylight hours',
                'price_info' => 'No fixed fee',
                'getting_there' => 'Short drive from Wabag Town.',
                'safety_notes' => 'Return before dark.',
                'contact_info' => 'Local guides on request.',
                'icon' => 'nature',
                'link_label' => 'Explore',
                'sort_order' => 19,
            ],
            [
                'category_label' => 'NATURE',
                'title' => 'Wildflower Season Walks',
                'description' => 'Seasonal walks with wildflowers and alpine plants.',
                'detail_intro' => 'A seasonal highlight for nature enthusiasts.',
                'highlights' => $list([
                    'Wildflower meadows in season',
                    'Cool mountain air',
                    'Scenic short walks',
                ]),
                'tips' => $list([
                    'Ask locals about peak bloom times',
                ]),
                'checklist' => $list([
                    'Camera or phone',
                ]),
                'itinerary' => $list([
                    'Morning walk during bloom season',
                ]),
                'locations' => $list([
                    'Highland slopes near Wabag',
                ]),
                'best_time' => 'Seasonal bloom periods',
                'duration' => '1–2 hours',
                'difficulty' => 'Easy',
                'opening_hours' => 'Daylight hours',
                'price_info' => 'No fixed fee',
                'getting_there' => 'Local transport from Wabag Town.',
                'safety_notes' => 'Stay on paths to protect plants.',
                'contact_info' => 'Local guides can advise best times.',
                'icon' => 'nature',
                'link_label' => 'Explore',
                'sort_order' => 20,
            ],

            // COMMUNITY & CRAFTS (5)
            [
                'category_label' => 'COMMUNITY',
                'title' => 'Local Artisans & Bilum Weaving',
                'description' => 'Meet artisans who create traditional bilums and textiles.',
                'detail_intro' => 'Learn about techniques, patterns, and cultural meaning.',
                'highlights' => $list([
                    'Traditional bilum weaving',
                    'Natural dyes and patterns',
                    'Support local makers',
                ]),
                'tips' => $list([
                    'Ask about the story behind each design',
                    'Buy directly from makers',
                ]),
                'checklist' => $list([
                    'Small cash for purchases',
                ]),
                'itinerary' => $list([
                    'Visit artisan area',
                    'Observe weaving',
                    'Purchase local crafts',
                ]),
                'locations' => $list([
                    'Artisan stalls in Wabag',
                ]),
                'best_time' => 'Daytime',
                'duration' => '1–2 hours',
                'difficulty' => 'Easy',
                'opening_hours' => 'Daytime hours',
                'price_info' => 'Varies by item',
                'getting_there' => 'Accessible from Wabag Town markets.',
                'safety_notes' => 'Keep valuables secure.',
                'contact_info' => 'Market staff can point to artisan stalls.',
                'icon' => 'community',
                'link_label' => 'Discover',
                'sort_order' => 21,
            ],
            [
                'category_label' => 'COMMUNITY',
                'title' => 'Wood Carving & Sculpture',
                'description' => 'Traditional carving skills passed down across generations.',
                'detail_intro' => 'See carving techniques and symbolic motifs.',
                'highlights' => $list([
                    'Traditional carving demonstrations',
                    'Cultural symbolism in designs',
                    'Opportunity to purchase local art',
                ]),
                'tips' => $list([
                    'Ask before taking photos',
                ]),
                'checklist' => $list([
                    'Small cash for crafts',
                ]),
                'itinerary' => $list([
                    'Visit carving workshop',
                    'Observe demonstration',
                ]),
                'locations' => $list([
                    'Community workshops near Wabag',
                ]),
                'best_time' => 'Daytime',
                'duration' => '1–2 hours',
                'difficulty' => 'Easy',
                'opening_hours' => 'By arrangement',
                'price_info' => 'Varies by item',
                'getting_there' => 'Arrange visit with local coordinators.',
                'safety_notes' => 'Follow workshop safety guidance.',
                'contact_info' => 'District cultural office can assist.',
                'icon' => 'community',
                'link_label' => 'Discover',
                'sort_order' => 22,
            ],
            [
                'category_label' => 'COMMUNITY',
                'title' => 'Community‑Led Tours',
                'description' => 'Guided visits hosted by local communities in Wabag District.',
                'detail_intro' => 'Learn about daily life, gardens, and traditions.',
                'highlights' => $list([
                    'Local hosts and community stories',
                    'Village gardens and livelihoods',
                    'Cultural exchange',
                ]),
                'tips' => $list([
                    'Bring a small gift for hosts',
                    'Be respectful of local customs',
                ]),
                'checklist' => $list([
                    'Small gift or contribution',
                ]),
                'itinerary' => $list([
                    'Meet host community',
                    'Village tour and garden visit',
                    'Shared refreshments',
                ]),
                'locations' => $list([
                    'Village communities around Wabag',
                ]),
                'best_time' => 'By arrangement',
                'duration' => 'Half day',
                'difficulty' => 'Easy to moderate',
                'opening_hours' => 'By arrangement',
                'price_info' => 'Community contribution appreciated',
                'getting_there' => 'Coordinate transport with hosts or local guides.',
                'safety_notes' => 'Follow host guidance at all times.',
                'contact_info' => 'District office can connect you with communities.',
                'icon' => 'community',
                'link_label' => 'Discover',
                'sort_order' => 23,
            ],
            [
                'category_label' => 'COMMUNITY',
                'title' => 'Youth Sports & Community Fields',
                'description' => 'Community sports gatherings and open fields in Wabag.',
                'detail_intro' => 'A chance to see local sports culture and community events.',
                'highlights' => $list([
                    'Community sports gatherings',
                    'Local youth participation',
                    'Open field events',
                ]),
                'tips' => $list([
                    'Ask permission before photographing',
                    'Respect local event schedules',
                ]),
                'checklist' => $list([
                    'Sun protection',
                ]),
                'itinerary' => $list([
                    'Visit community field',
                    'Observe games and activities',
                ]),
                'locations' => $list([
                    'Community fields in Wabag Town',
                ]),
                'best_time' => 'Weekends and community event days',
                'duration' => '1–2 hours',
                'difficulty' => 'Easy',
                'opening_hours' => 'Daylight hours',
                'price_info' => 'Free to observe',
                'getting_there' => 'Accessible from Wabag Town.',
                'safety_notes' => 'Stay clear of active play areas.',
                'contact_info' => 'Community leaders can share schedules.',
                'icon' => 'community',
                'link_label' => 'Discover',
                'sort_order' => 24,
            ],
            [
                'category_label' => 'COMMUNITY',
                'title' => 'Village Hospitality Visits',
                'description' => 'Short visits to host communities for cultural exchange.',
                'detail_intro' => 'Ideal for learning daily life, food, and customs.',
                'highlights' => $list([
                    'Home‑cooked local food',
                    'Cultural exchanges',
                    'Community storytelling',
                ]),
                'tips' => $list([
                    'Bring a small gift',
                    'Follow host protocols',
                ]),
                'checklist' => $list([
                    'Small gift or contribution',
                ]),
                'itinerary' => $list([
                    'Arrival and welcome',
                    'Cultural exchange and meal',
                ]),
                'locations' => $list([
                    'Host villages near Wabag',
                ]),
                'best_time' => 'By arrangement',
                'duration' => '2–4 hours',
                'difficulty' => 'Easy',
                'opening_hours' => 'By arrangement',
                'price_info' => 'Community contribution appreciated',
                'getting_there' => 'Arrange transport with hosts or guides.',
                'safety_notes' => 'Respect cultural guidelines.',
                'contact_info' => 'District office can assist with coordination.',
                'icon' => 'community',
                'link_label' => 'Discover',
                'sort_order' => 25,
            ],
        ];

        foreach ($records as $index => $record) {
            $title = $record['title'];
            ExploreWabagItem::updateOrCreate(
                ['title' => $title],
                array_merge($record, [
                    'slug' => Str::slug($title),
                    'is_published' => true,
                ])
            );
        }
    }
}
