<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Project;
use Illuminate\Support\Carbon;
use Faker\Factory;

class ProjectSeeder extends Seeder
{
    public function run(): void
    {
        $faker = Factory::create();
        Project::insert([
            [
                'project_code' => 'PRJ-001',
                'title' => 'Highlands Road Rehabilitation',
                'project_type_id' => 1,
                'funding_source_id' => 1,
                'llg_id' => 1,
                'ward_id' => 1,
                'location' => 'Lakemanda, Wabag',
                'coordinates' => '-5.4789, 143.7201',
                'budget' => 1200000,
                'amount_spent' => 1150000,
                'progress_percentage' => 95,
                'start_date' => '2024-01-10',
                'expected_end_date' => '2024-06-30',
                'actual_end_date' => '2024-07-05',
                'status' => 'completed',
                'is_public' => true,
                'published_at' => Carbon::now(),
                'description' => 'Rehabilitation of major highlands highway for improved transportation.',
                'featured_image' => $faker->imageUrl(800, 600, 'projects', true),
                'featured_image' => '/wabag-dda/public/images/about-us/slide-img/hospital-upgrade.jpg',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'project_code' => 'PRJ-002',
                'title' => 'Rural Health Centre Construction',
                'project_type_id' => 2,
                'funding_source_id' => 2,
                'llg_id' => 2,
                'ward_id' => 5,
                'location' => 'Tukusanda, Wabag',
                'coordinates' => '-5.5102, 143.7555',
                'budget' => 800000,
                'amount_spent' => 450000,
                'progress_percentage' => 60,
                'start_date' => '2024-03-01',
                'expected_end_date' => '2024-10-30',
                'actual_end_date' => null,
                'status' => 'in_progress',
                'is_public' => true,
                'published_at' => Carbon::now(),
                'description' => 'Construction of a new rural health centre to improve access to basic health care.',
                'featured_image' => 'projects/featured-images/health.jpg',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'project_code' => 'PRJ-003',
                'title' => 'Community Water Supply Project',
                'project_type_id' => 3,
                'funding_source_id' => 1,
                'llg_id' => 3,
                'ward_id' => 6,
                'location' => 'Teremanda, Wabag',
                'coordinates' => '-5.4890, 143.7322',
                'budget' => 500000,
                'amount_spent' => 480000,
                'progress_percentage' => 100,
                'start_date' => '2023-11-01',
                'expected_end_date' => '2024-02-28',
                'actual_end_date' => '2024-03-02',
                'status' => 'completed',
                'is_public' => true,
                'published_at' => Carbon::now(),
                'description' => 'Community water supply system for reliable clean water access.',
                'featured_image' => 'projects/featured-images/water.jpg',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'project_code' => 'PRJ-004',
                'title' => 'Primary School Classrooms Extension',
                'project_type_id' => 2,
                'funding_source_id' => 3,
                'llg_id' => 1,
                'ward_id' => 8,
                'location' => 'Sapos, Wabag',
                'coordinates' => '-5.4710, 143.7055',
                'budget' => 300000,
                'amount_spent' => 150000,
                'progress_percentage' => 50,
                'start_date' => '2024-02-15',
                'expected_end_date' => '2024-08-15',
                'actual_end_date' => null,
                'status' => 'in_progress',
                'is_public' => false,
                'published_at' => null,
                'description' => 'Expansion of classrooms to accommodate growing number of students.',
                'featured_image' => 'projects/featured-images/school.jpg',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'project_code' => 'PRJ-005',
                'title' => 'ICT Infrastructure Upgrade',
                'project_type_id' => 4,
                'funding_source_id' => 2,
                'llg_id' => 2,
                'ward_id' => 9,
                'location' => 'Aipus, Wabag',
                'coordinates' => '-5.5021, 143.7169',
                'budget' => 1500000,
                'amount_spent' => 1400000,
                'progress_percentage' => 90,
                'start_date' => '2023-09-01',
                'expected_end_date' => '2024-05-01',
                'actual_end_date' => '2024-05-15',
                'status' => 'completed',
                'is_public' => true,
                'published_at' => Carbon::now(),
                'description' => 'Upgrading ICT systems in government offices for better connectivity and service delivery.',
                'featured_image' => 'projects/featured-images/ict.jpg',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'project_code' => 'PRJ-006',
                'title' => 'Market Facility Rehabilitation',
                'project_type_id' => 1,
                'funding_source_id' => 3,
                'llg_id' => 3,
                'ward_id' => 11,
                'location' => 'Yupirak, Wabag',
                'coordinates' => '-5.4953, 143.7287',
                'budget' => 950000,
                'amount_spent' => 900000,
                'progress_percentage' => 100,
                'start_date' => '2024-01-15',
                'expected_end_date' => '2024-06-30',
                'actual_end_date' => '2024-06-28',
                'status' => 'completed',
                'is_public' => true,
                'published_at' => Carbon::now(),
                'description' => 'Rehabilitation of major market facility to improve local economic activity.',
                'featured_image' => 'projects/featured-images/market.jpg',
                'created_by' => 1,
                'updated_by' => 1,
            ],
        ]);
    }
}
